# Blue-Green Deployment Workflow

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  # Check which environment is currently active
  get-active-environment:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.set-env-output.outputs.env }}
      project_dir: ${{ steps.set-env-output.outputs.project_dir }}

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

      - name: Determine current environment
        id: get-active
        run: |
          ssh -p 65002 -o StrictHostKeyChecking=no u605848448@217.21.77.232 \
          'readlink /home/u605848448/domains/michael-gibbs-testing.site/public_html/current || echo "ERROR"' > current_env.txt
          if [ ! -s current_env.txt ]; then
            echo "ERROR: No environment file found or permission denied" > current_env.txt
          fi

      - name: Set environment based on active
        id: set-env-output
        run: |
          env_value=$(cat current_env.txt | tr -d '\n' | tr -d '\r')  # Remove newlines or carriage returns
          echo "Environment value: $env_value"  # Debugging
          echo "env=$env_value" >> $GITHUB_ENV

          # Set project directory based on environment
          if [[ "$env_value" == "/home/u605848448/domains/michael-gibbs-testing.site/blue/public/" ]]; then
            project_dir="/home/u605848448/domains/michael-gibbs-testing.site/blue/"
          else
            project_dir="/home/u605848448/domains/michael-gibbs-testing.site/green/"
          fi
          echo "project_dir=$project_dir" >> $GITHUB_ENV
          echo "::set-output name=env::$env_value"
          echo "::set-output name=project_dir::$project_dir"

      - name: Output environment value
        run: |
          echo "Environment: ${{ steps.set-env-output.outputs.env }}"
          echo "Project Directory: ${{ steps.set-env-output.outputs.project_dir }}"

  deploy:
    runs-on: ubuntu-latest
    needs: get-active-environment
    steps:
      - name: Output environment values
        run: |
          echo "Environment: ${{ needs.get-active-environment.outputs.env }}"  # Access output from previous job
          echo "Project Directory: ${{ needs.get-active-environment.outputs.project_dir }}"
