name: Test SSH Connection

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug SSH Key
        run: echo "$HOSTINGER_SSH_KEY" | head -n 5
        env:
          HOSTINGER_SSH_KEY: ${{ secrets.HOSTINGER_SSH_KEY }}

      