name: Test FTP Connection

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test-ftp:
    runs-on: ubuntu-latest

    steps:
      - name: Test FTP Connection
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: "./" # Empty test directory; no files are transferred
          server-dir: "/" # Root directory of the FTP server
          dry-run: true # Ensures no files are uploaded during the test

      - name: Verify Connection Success
        run: |
          echo "FTP connection successful. Credentials and server are valid."
